# Generated by Django 4.2.7 on 2025-12-24 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_hours', models.IntegerField(help_text='Продолжительность маршрута в часах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (часы)')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Бюджет')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Расстояние (км)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранный')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(default=list, help_text='Список интересов пользователя', verbose_name='Интересы')),
                ('preferred_duration_min', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Минимальная длительность (мин)')),
                ('preferred_duration_max', models.IntegerField(default=480, validators=[django.core.validators.MinValueValidator(60)], verbose_name='Максимальная длительность (мин)')),
                ('max_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Максимальный бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='user_preferences', to='attractions.category', verbose_name='Предпочитаемые категории')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предпочтения пользователя',
                'verbose_name_plural': 'Предпочтения пользователей',
            },
        ),
        migrations.CreateModel(
            name='RouteAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('visit_duration', models.IntegerField(default=60, help_text='Продолжительность посещения в минутах', verbose_name='Длительность посещения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_attractions', to='attractions.attraction', verbose_name='Достопримечательность')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_attractions', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Достопримечательность маршрута',
                'verbose_name_plural': 'Достопримечательности маршрутов',
                'ordering': ['route', 'order'],
                'indexes': [models.Index(fields=['route', 'order'], name='routes_rout_route_i_6a831d_idx')],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user'], name='routes_rout_user_id_a8042b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_public'], name='routes_rout_is_publ_969257_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['-views_count'], name='routes_rout_views_c_2c1f25_idx'),
        ),
    ]
